spring.application.name=task-buddy-be
spring.mongodb.uri=mongodb://localhost:27017/task-buddy

spring.data.mongodb.auto-index-creation=true
server.port=8090

spring.jackson.mapper.accept-case-insensitive-enums=true