spring.application.name=task-buddy-be
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/task-buddy}

spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8090}

spring.jackson.mapper.accept-case-insensitive-enums=true